# Generated by Django 4.0.1 on 2022-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.IntegerField(default=''),
        ),
    ]
