# Generated by Django 4.0.1 on 2022-04-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
